### ISSUE TITLE
How can one change the default layout?

### ISSUE THREAD

**Issue by patsplat** [cruddy/cruddy#101]
In FrozenNode one can override the default views without editing core files:

https://github.com/FrozenNode/Laravel-Administrator/issues/144#issuecomment-70147117

Trying to do something similar in app/config/packages/kalnoy/cruddy/config.php:

```php
View::prependNamespace('cruddy', '/path/to/views');
```

Will this be possible w/ Cruddy?

**Comment by lazychaser** [comment]
Hi, in Cruddy there is only one view file that is used to compile everything together, and then JavaScript is taking place

**Comment by patsplat** [comment]
Thanks for the response.  Yes, cruddy's frontend is clean and mostly js.  I
am just trying to override that one view without editing the cruddy src.

Need to add branding which goes beyond normal options.  Can make it
compatible with cruddy's frontend - just looking for a clean way to
override the template.

Let me know if you think of anything.

Cheers,

Patrick

**Comment by lazychaser** [comment]
I'll see what I can do

**Comment by lazychaser** [comment]
You can now alter views after publishing them:

```php
php artisan vendor:publish
```

They will become available under `resource/views/vendor/cruddy`.

**Comment by patsplat** [comment]
Thanks!  Current project is laravel 4.2, will setup a 5.x to test the enhancement.
