### ISSUE TITLE
file deletion

### ISSUE THREAD

**Issue by flinguin** [cruddy/cruddy#102]
with uploads the documentation suggests implementing the deletion of an uploaded file/image via a model event ... in laravel 5 using an EventServiceProvider it would look like this:
```php
public function boot(DispatcherContract $events)
{
   parent::boot($events);

   Post::deleted(function($post)
    	{
    		if ($post->image) File::delete(public_path($post->image));
    	});
}
```

but this way the file/image only gets deleted when the entry is deleted - is it possible to also delete files if an entry is updated and a new file/image was uploaded? in this case i would like to delete the old file on the server and store the new one ... and for sure i just want to do it if a new file was uploaded ;)

**Comment by flinguin** [comment]
also ... if an earlier uploaded file is just removed from an entry (and no new file is uploaded) the file should ideally be removed from the server.

**Comment by lazychaser** [comment]
You should rather use `Post::saving` event to check whether the value of the file source is changed by using `$model->getDirty()` and delete the file if it was.
