### ISSUE TITLE
array_key_exists Error

### ISSUE THREAD

**Issue by ehsanmnz** [cruddy/cruddy#103]
After loading all menu entities if I click on one entity this error appears
array_key_exists(): The first argument should be either a string or an integer
and if even page hard reloaded, this error still appears

**Comment by lazychaser** [comment]
Please, provide full error description from the log file.

**Comment by ehsanmnz** [comment]
I use the middleware to obfuscating some sensitive data and decode those, by modifying this middleware the exception is gone
full error description
exception 'ErrorException' with message 'array_key_exists(): The first argument should be either a string or an integer'
Thanks
