### ISSUE TITLE
menu & service_menu - permission

### ISSUE THREAD

**Issue by flinguin** [cruddy/cruddy#104]
trying to restrict some of my menu or service_menu items to "admin only" i ran into this error:
(using latest laravel5 & cruddy master)

>ErrorException in helpers.php line 455:
>htmlentities() expects parameter 1 to be string, object given (View: >/var/www/rio/resources/views/vendor/cruddy/layout.blade.php) (View: >/var/www/rio/resources/views/vendor/cruddy/layout.blade.php)

the corresponding cruddy configuration looks like this:

```php
...
'service_menu' => [
    [ 
        'label' => 'Admin only',
        'items' => [  
            ...
        ],
        'icon' => 'cog',
        'permissions' => function () { Auth::user()->isAdmin(); }
    ]
],
...
```

any suggestions on how to get the closure accepted or what i am doing wrong ?
thanks

**Comment by lazychaser** [comment]
There has been changes to menu options, see this: https://github.com/lazychaser/illuminate-menu

In your case you need to change `permissions` to `visible`.
