### ISSUE TITLE
Permission Type Hint Exception

### ISSUE THREAD

**Issue by ehsanmnz** [cruddy/cruddy#105]
Hi, after update and publish, we have this exception:

Declaration of App\Entities\Permissions\BackendPermissions::isPermitted() must be compatible with Kalnoy\Cruddy\Contracts\Permissions::isPermitted($action, Kalnoy\Cruddy\BaseForm $entity

**Comment by lazychaser** [comment]
Just switch `Entity` to `BaseForm`. Later there will be separate forms that can be used for some processing and for entering parameters for actions.

**Comment by ehsanmnz** [comment]
Thanks
