### ISSUE TITLE
Сохранение Даты

### ISSUE THREAD

**Issue by Jok3r11of** [cruddy/cruddy#108]
При вводе даты 2015-01-12  в БД сохранят на минус 1 день, при чём все даты. Не пойму почему, не поможете?

**Comment by lazychaser** [comment]
это все как-то связано с натройками mysql и laravel, у них там разная
временная зона, насколько я помню

8 июля 2015 г., 14:00 пользователь Jok3r11of <notifications@github.com>
написал:

> При вводе даты 2015-01-12 в БД сохранят на минус 1 день, при чём все даты.
> Не пойму почему, не поможете?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cruddy/cruddy/issues/108>.
>



-- 
Best regards, Alexander Kalnoy.

**Comment by Jok3r11of** [comment]
Смотрел при отправке $schema->date('column');
Отпровляет не в дате а именно в Timestamp, смотрел запрос POST копировал TImestamp который отпровял, уже дата -1. то есть я пишу 2015-12-14 нажимаю Save после конверта в Timestamp отпровляет в БД -1 день. что кто не думаю что это трабл с MYSQL. Хз если понятно объяснил))

**Comment by uldisrudzitis** [comment]
check the config/app.php for timezone

**Comment by Jok3r11of** [comment]
@uldisrudzitis yes worked. Forgot to change that. Thank you.

**Comment by lazychaser** [comment]
Проблема решена?

**Comment by Jok3r11of** [comment]
@lazychaser Да Александр спасибо.
