### ISSUE TITLE
how to set Permission driver?

### ISSUE THREAD

**Issue by cwiggan** [cruddy/cruddy#109]
I am using entrust and confide together. 

How do i define 
'permissions' => 'zizaco/entrust',

?

**Comment by lazychaser** [comment]
`permissions` is a class name that will be resolved out of IoC container and must implement https://github.com/cruddy/cruddy/blob/master/src/Contracts/Permissions.php

**Comment by cwiggan** [comment]
can you provide an example, please.

**Comment by lazychaser** [comment]
Here is the example from my working project: https://gist.github.com/lazychaser/69e061bd35693a6d1b7e

```php
'permissions' => \App\Backend\Permissions::class,
```
