### ISSUE TITLE
running cruddy when laravel is not the root folder

### ISSUE THREAD

**Issue by jamesearlywine** [cruddy/cruddy#110]
How can I run cruddy in a subdirectory?  The client-side router seems to assume that cruddy is running from the vhost root.  Any tips/hints on where I can look to adjust that?

**Comment by jamesearlywine** [comment]
nevermind, I hacked the vendor code in a few places and made it work.

--jle

**Comment by lazychaser** [comment]
Which version you use? 0.5.0@dev should work correctly outside root. So, please describe your issue more specifically.

**Comment by jamesearlywine** [comment]
I have the same problem with 0.5.0:
http://hssticker.indystardev.com/backend/public/index.php/admincms

**Comment by jamesearlywine** [comment]
Also the loader bars aren't going away sometimes

**Comment by jamesearlywine** [comment]
If you click an item, the dynamically-generated url part chops off the subfolder, such that if you refresh the page, it gives a 404

**Comment by jamesearlywine** [comment]
Is there something I don't know that can resolve this?  I upgraded to 0.5.0, and am wondering if I need to integrate my hack from my old version to the new version.

--jle
