### ISSUE TITLE
Maximum function nesting level of '100' reached, aborting!

### ISSUE THREAD

**Issue by taghaniali** [cruddy/cruddy#111]
i have a messages table in my db with five fields (id,full_name,email,subject,body) . writing 'schema->increments('id');' in fields method of MessageSchema produce " Maximum function nesting level of '100' reached, aborting! " , and if i comments that line the app works but i can not edit a row in cruddy .
what is the problem ?

**Comment by lazychaser** [comment]
What version? 0.5?

**Comment by taghaniali** [comment]
Version 0.5

On Tue, Oct 20, 2015 at 11:40 AM, Alexander Kalnoy <notifications@github.com
> wrote:

> What version? 0.5?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cruddy/cruddy/issues/111#issuecomment-149470943>.
>



-- 
Regards,
Taghani Ali.

**Comment by ehsanmnz** [comment]
disabled x-debug or set xdebug.max_nesting_level to the 130 or upper in php.ini

**Comment by lazychaser** [comment]
Yes, this should help

**Comment by taghaniali** [comment]
thanks this solution solved the problem.
Was that the correct thing to do? It fixes the problem but always seems odd to me to need to edit an ini file for an application. I find it odd because we don't always have access in a production env to edit ini files but since this is only happening during testing I have complete control so I only question what exactly causes this. Is it a bug? Or just something that happens in testing?

**Comment by lazychaser** [comment]
You also don't have xdebug turned on in production. It fine solution for
now.

2015-10-20 11:31 GMT+03:00 taghaniali <notifications@github.com>:

> thanks this solution solved the problem.
> Was that the correct thing to do? It fixes the problem but always seems
> odd to me to need to edit an ini file for an application. I find it odd
> because we don't always have access in a production env to edit ini files
> but since this is only happening during testing I have complete control so
> I only question what exactly causes this. Is it a bug? Or just something
> that happens in testing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cruddy/cruddy/issues/111#issuecomment-149477127>.
>



-- 
Best regards, Alexander Kalnoy.

**Comment by ehsanmnz** [comment]
for production environment this option always disabled by default

**Comment by taghaniali** [comment]
ok. you are right. thanks again

On Tue, Oct 20, 2015 at 12:03 PM, Alexander Kalnoy <notifications@github.com
> wrote:

> You also don't have xdebug turned on in production. It fine solution for
> now.
>
> 2015-10-20 11:31 GMT+03:00 taghaniali <notifications@github.com>:
>
> > thanks this solution solved the problem.
> > Was that the correct thing to do? It fixes the problem but always seems
> > odd to me to need to edit an ini file for an application. I find it odd
> > because we don't always have access in a production env to edit ini files
> > but since this is only happening during testing I have complete control
> so
> > I only question what exactly causes this. Is it a bug? Or just something
> > that happens in testing?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cruddy/cruddy/issues/111#issuecomment-149477127>.
> >
>
>
>
> --
> Best regards, Alexander Kalnoy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cruddy/cruddy/issues/111#issuecomment-149477330>.
>



-- 
Regards,
Taghani Ali.

**Comment by taghaniali** [comment]
and thanks mr. minaei

**Comment by ehsanmnz** [comment]
your welcome :)
