### ISSUE TITLE
how to exclude a field from insertion to db?

### ISSUE THREAD

**Issue by taghaniali** [cruddy/cruddy#112]
Hi,
two question 
1- how to insert a computed field into db. for example i want to store hash value of password field into db
2- how to exclude a field from insertion to db for example i have a password and password_confirmation field but i do not want to store password_confirmation field. but now cruddy inserts all field into db and this produce insertion error .
thanks

**Comment by lazychaser** [comment]
1. Use attribute setter for hashing, computed fields are only for displaying
2. You can define an empty attribute setter

2015-10-26 9:37 GMT+03:00 taghaniali <notifications@github.com>:

> Hi,
> two question
> 1- how to insert a computed field into db. for example i want to store
> hash value of password field into db
> 2- how to exclude a field from insertion to db for example i have a
> password and password_confirmation field but i do not want to store
> password_confirmation field. but now cruddy inserts all field into db and
> this produce insertion error .
> thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cruddy/cruddy/issues/112>.
>



-- 
Best regards, Alexander Kalnoy.

**Comment by taghaniali** [comment]
thanks.

**Comment by taghaniali** [comment]
2. the password_confirmation field is not a field of my table and i use it only for validating password confirmation. so i want to exclude value of that from insert query. the empty attribute will be helpful when that field is in table.

**Comment by lazychaser** [comment]
Add to your model:

public function setPasswordConfirmationAttribute() {};

2015-10-26 10:11 GMT+03:00 taghaniali <notifications@github.com>:

>
>    1. the password_confirmation field is not a field of my table and i
>    use it only for validating password confirmation. so i want to exclude
>    value of that from insert query. the empty attribute will be helpful when
>    that field is in table.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cruddy/cruddy/issues/112#issuecomment-151046947>.
>



-- 
Best regards, Alexander Kalnoy.

**Comment by taghaniali** [comment]
ok very good it solved the problem.
thanks alot.
