### ISSUE TITLE
Laravel 5, Embedded Forms, Markdown Field

### ISSUE THREAD

**Issue by foxhound87** [cruddy/cruddy#113]
I'm updating a project to laravel 5.1 and found some issues on cruddy.
The markdown Field don't work: "RuntimeException: Macro [markdown] is not registered"
This is the stack trace: https://gist.github.com/foxhound87/53aa9de3cfbab7066890
The Embedded Forms are not working at all, no errors are shown, just the content is not loaded into the form.

I'm using "kalnoy/cruddy": "0.5.*@dev"

**Comment by lazychaser** [comment]
You need this extension to enable markdown: https://github.com/cruddy/ace

**Comment by foxhound87** [comment]
Great, Markdown is working, what about the Embedded Forms? 
The issue occurs on "hasMany" relations types, but it works using "hasOne"!

**Comment by lazychaser** [comment]
Console has no errors?
Form doesn't have any controls related to your field?

2015-11-08 17:05 GMT+03:00 Claudio Savino <notifications@github.com>:

> Great, Markdown is working, what about the Embedded Forms?
> The issue occurs on "hasMany" relations types, but it works using "hasOne"!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cruddy/cruddy/issues/113#issuecomment-154828581>.
>



-- 
Best regards, Alexander Kalnoy.

**Comment by foxhound87** [comment]
No errors on console,
the related data is retrieved and present in the json returned by that point.
I suppose is something related to the js frontend logic that doesn't update the UI.

**Comment by lazychaser** [comment]
It works fine with my demo setup using HasMany relation. Are you using layout feature? Maybe some specific models layout? Would be great to see source models and entities.

**Comment by foxhound87** [comment]
Can I send a bitbucket repository to your private email? 
thank you for your support.

**Comment by lazychaser** [comment]
Yeah, I guess. Never worked with BitBucket, but I think I'll figure it out.

2015-11-08 19:03 GMT+03:00 Claudio Savino <notifications@github.com>:

> Can I send a bitbucket repository to your private email?
> thank you for your support.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cruddy/cruddy/issues/113#issuecomment-154835317>.
>



-- 
Best regards, Alexander Kalnoy.

**Comment by vahidies** [comment]
"It works fine with my demo setup using HasMany relation. Are you using layout feature? Maybe some specific models layout? Would be great to see source models and entities."

hi. I installed fresh laravel 5.1.23 and a cruddy "0.5.*@dev" and just two model with the one-to-many relation. but it doesn't work in hasMany embed. when i make new row and fill the inputs , after saving my row become deleted, but it saves in the database. and also there is no error in console or any where. thank for taking care of this issue :D

**Comment by lazychaser** [comment]
All should go as expected, the bug has been found and fixed. Thanks!
