### ISSUE TITLE
PHP7 Compatibility

### ISSUE THREAD

**Issue by solie** [cruddy/cruddy#114]
Using PHP 7.0.1 from homebrew, I got a Fatal Error: `Cannot use 'String' as class name as it is reserved in vendor/kalnoy/cruddy/src/Schema/Fields/Types/String.php on line 17`, no problem at all using PHP 5.5.30 from OSX El Capitan.

**Comment by lazychaser** [comment]
Sorry, PHP 7 is not a priority task, I'll take a look later.

**Comment by lazychaser** [comment]
I renamed some classes and this should fix your error.

**Comment by solie** [comment]
Wow, so fast! I will try tonight. Thanks.

**Comment by solie** [comment]
I have tried on my machine using PHP 7.0.1 and working good. Thanks!

**Comment by lazychaser** [comment]
Great!
