### ISSUE TITLE
Custom validate error messages

### ISSUE THREAD

**Issue by MaximKiselev** [cruddy/cruddy#115]
Привет, странно у вас как то работают сообщения для ошибок.  Хотя по идее, должен выдаваться JSON, а не Exception.

`ValidationException in BaseFormData.php line 38:`
```
  $v->always([
            'title' => 'required|max:100',
        ]);
        $v->messages(['title.required'=>'This field is required']);
```
`$schema->string('title')->required();`

В чем подвох?
laravel 5.2

**Comment by lazychaser** [comment]
В чем проблема? Этот эксепшн перехватывается в middleware и возвращается JSON

**Comment by MaximKiselev** [comment]
Он по умолчанию перехватывается?

**Comment by lazychaser** [comment]
Естественно

2016-01-05 10:22 GMT+03:00 Maxim Kiselev <notifications@github.com>:

> Он по умолчанию перехватывается?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cruddy/cruddy/issues/115#issuecomment-168922058>.
>



-- 
Best regards, Alexander Kalnoy.

**Comment by MaximKiselev** [comment]
Так вангую, что не перехватывается.

**Comment by lazychaser** [comment]
Версия cruddy какая?

2016-01-05 10:26 GMT+03:00 Maxim Kiselev <notifications@github.com>:

> Так вангую, что не перехватывается.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cruddy/cruddy/issues/115#issuecomment-168922770>.
>



-- 
Best regards, Alexander Kalnoy.

**Comment by MaximKiselev** [comment]
У меня тут еще вопросец назрел. Вообщем посмотрел, обработчик. HandleCruddyExceptions не обрабатывает нормально ошибки валидатора почему-то. Пробовал свое Middleware всунуть в EntityContoller - все сработало. Подключал под разному Kernel, в роуты .. толку нет. Можно только тупо перехватить ошибки валидатора в контроллере и тогда все работает...
