### ISSUE TITLE
Title in entity dropdown as HTML

### ISSUE THREAD

**Issue by h-collector** [cruddy/cruddy#118]
Just an idea for enhancement but following changes in commit 1b435c784ade8c29f54b444b39d06f148204adb1 .
Maybe we could also have some option to safely display entity title as html
![selection_257](https://cloud.githubusercontent.com/assets/3104787/12170410/92c26fee-b541-11e5-8dd5-f002db73945f.png)

As of now there is a problem with document.title and selection
 ![selection_259](https://cloud.githubusercontent.com/assets/3104787/12170307/86fbbe28-b540-11e5-9a9c-932f84de83c3.png)
![selection_258](https://cloud.githubusercontent.com/assets/3104787/12170411/92c7bfd0-b541-11e5-98a6-7f7a8c22898d.png)
But html tags could be stripped altogether for title and selected related entity (or not encoded like using `Plain` formatter on column).
(* not really sure how would searching work)

**Comment by lazychaser** [comment]
Good idea!

We could also display actual preview for media items rather than path.

> As of now there is a problem with document.title and selection
I could add `documentTitle` function (same as `toString`) which will strip html tags as a default behaviour.

> (* not really sure how would searching work)
Searching works based on actual data in database, computed properties (title is a computed property) do not count.

**Comment by lazychaser** [comment]
You can now test it. Will be available in `0.5.6`. Available now in `0.5.6@dev`. You can see example [here](https://github.com/cruddy/docs/blob/master/Schema.md#setting-title-attribute-property).

**Comment by h-collector** [comment]
It works very nicely :thumbsup: 
But there is one still one problem through. If you edit related item, then it sets wrongly plain value and not the HTML one (if I'm not mistaken then the problem is in entityDropdown edit method)

**Comment by lazychaser** [comment]
Oh yeah, I missed this one, thanks

**Comment by h-collector** [comment]
Just one more suggestion, shouldn't items rendered in entitySelector also be refreshed after adding new or updating existing entity?
Refreshing manually (by button) works, but maybe triggering datasource refresh or updating/appending item by default would be less confusing.

**Comment by lazychaser** [comment]
Makes sence.

**Comment by lazychaser** [comment]
@h-collector thanks for qualitative response. Now datasource refresh is triggered when instance updated or created.
