### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by M0H3N** [cruddy/cruddy#119]
Hi 
After run composer require kalnoy/cruddy:~0.5.0  the package installed successfully but after run 
"php artisan vendor:publish --provider="Kalnoy\Cruddy\CruddyServiceProvider" 

I encountered with this message 
Nothing to publish for tag [] 

whats the problem ? 
thanks

**Comment by lazychaser** [comment]
Hmm... try `php artisan vendor:publish --tag public`

**Comment by M0H3N** [comment]
I tried that but same error happened again :
Nothing to publish for tag [public]

**Comment by lazychaser** [comment]
Ah, maybe you forgot to add the service provider to the configuration?
27 янв. 2016 г. 21:23 пользователь "M0H3N" <notifications@github.com>
написал:

**Comment by M0H3N** [comment]
ah ... yes I forgot that ...  sorry 
thanks a lot

**Comment by EH7AN** [comment]
Hi i have same problem, where should i add the service provider!?  I think i add it but i get this error
Class 'Kalnoy\Cruddy\Cruddy Service Provider'

**Comment by EH7AN** [comment]
Class 'Kalnoy\Cruddy\Cruddy Service Provider' not found

**Comment by lazychaser** [comment]
@EH7AN why spaces in class name?

**Comment by EH7AN** [comment]
Sorry that was my mistype. After i installed laravel 5.2 i also install cruddy with composer in my app directory then i run the following command:
php artisan vendor:publish --provider="Kalony\Cruddy\CruddyServiceProvider"
And i encountered with same problem as mentioned in previous comments about tag[] as u said i add the Kalomy provider service in my config/app file  at the end of my providers array then i run the same php artisan command this time the error was:
[Symfony\Component\Debug\Exception\FatalErrorException]                                             Class 'Kalnoy\Cruddy\CruddyServiceProvider' not found
So, what's wrong!?

**Comment by M0H3N** [comment]
@EH7AN
بعد اینکه کرادی رو نصب کردی باید سرویس پرووایدر رو اضافه کنی بعدش وندور پابلیش کنی

**Comment by EH7AN** [comment]
@M0H3N
راهنمایی میکنی چطور باید سروس پروایدر رو اضافه کنم. متشکرم

**Comment by M0H3N** [comment]
config   تویه فولدر 
app.php فایل 
 providers به ارایه 
:اینو اضافه کن 
Kalnoy\Cruddy\CruddyServiceProvider::class,

**Comment by EH7AN** [comment]
آقا کاری که گفتی رو هم قبلا انجام دائه بودم بعد که پابلیش کردم این ارور رو به من داد :
[Symfony\Component\Debug\Exception\FatalErrorException] Class 
'Kalnoy\Cruddy\CruddyServiceProvider'  not found   
من این کامند رو ران کردم
php artisan vendor:publish --provider="Kalony\Cruddy\CruddyServiceProvider"

**Comment by M0H3N** [comment]
راه نصبش همونه  راه دیگه ای نداره 
البته من بعد اینکه این ارور رو داد یه بار پکیج رو پاک کردم از اول نصب کردم درست شد 
باید وایسی تا پکیج کامل نصب بشه بعد سرویسشو اضافه کنی
