### ISSUE TITLE
Argument to create entities in a specified folder

### ISSUE THREAD

**Issue by mgarciadelojo** [cruddy/cruddy#121]
Hi,

First of all thank you very much for this awesome library. I've been using just for a couple of weeks but I would like to make one contribution to it. For me, "Entities" can be a lot confusing since I've been working for Doctrine, and I prefer to call them AdminEntities or only Admin.

In my opinion, the make:entity command should have a parameter that would allow users to specify the desired namespace or path in the system.

Just if you are open to it, I wanted to create a Pull Request :)

Best regards,

**Comment by lazychaser** [comment]
Hey, thank you!

You can use the command as follows: ```php artisan make:entity "App\Admin\MyEntity"```

Rename `App` to the namespace that your application uses if it's different.

**Comment by mgarciadelojo** [comment]
Ok!! Thank you very much!

Best regards
