### ISSUE TITLE
Disable create, update, delete

### ISSUE THREAD

**Issue by mgarciadelojo** [cruddy/cruddy#122]
Hi!

Firstly, thank you very much for this great library. It's very powerful!

The question is, I am creating a payment gateway and I am storing transactions into the DB, but I don't want to let users create, edit or delete them. I've been doing a little research in your code but I didn't find anything about it. Do you have any idea how can I handle this?

Thanks!

**Comment by uldisrudzitis** [comment]
You can restrict access with the help of this package: https://github.com/cruddy/sentry

**Comment by ehsanmnz** [comment]
You can implement this interface
https://github.com/cruddy/cruddy/blob/master/src/Contracts/Permissions.php#L10
and register here
https://github.com/cruddy/cruddy/blob/master/config/cruddy.php#L17
then you can access the actions (view/edit/...) and entities (transactions/....) here
https://github.com/cruddy/cruddy/blob/master/src/Contracts/Permissions.php#L10
finally write your own logic

**Comment by mgarciadelojo** [comment]
Yes @uldisrudzitis, @ehsanmnz , I thought about your solutions before because I just implemented a custom module to allow users manage simple permissions, but I don't want anyone to create, edit or delete rows in this entity.

Maybe, what I am going to do is to deny this actions hard-coded. I don't like so much doing this but...

Thanks!!

**Comment by lazychaser** [comment]
I use hardcoded values in some of my projects. Its fine :)
12 Фев 2016 г. 16:30 пользователь "Manuel García" <notifications@github.com>
написал:
