### ISSUE TITLE
Entity Title errors in dev-version

### ISSUE THREAD

**Issue by mgarciadelojo** [cruddy/cruddy#124]
Hi!!

I am using last version commited since I created the last pull-request, and I noticed that there are some issues fixed like validation and layouts, but, there are also some errors in relations.

Just to give you an example, all options in a relationship fields shows undefined. See image below.

![captura de pantalla de 2016-02-15 10 33 22](https://cloud.githubusercontent.com/assets/1866396/13044740/09e836ce-d3d0-11e5-9127-e754ce1f7125.png)

**Comment by lazychaser** [comment]
Please make sure you've updated cruddy assets using vendor:publish

**Comment by mgarciadelojo** [comment]
Ok, I just did it, but nothing happened! I tried to restart homestead, my browser, and clear cache as well :(

**Comment by mgarciadelojo** [comment]
Finally, I got it working by deleting the public/cruddy folder and executing: `php artisan vendor:publish --tag public` without the `--force` flag

**Comment by lazychaser** [comment]
Hmm, maybe something has changed with publising in recent version of
laravel. I'm glad that everything works. But this might change in near
future since huuuge refactoring to PHP part was done and will be available
soon

**Comment by mgarciadelojo** [comment]
Nice!! If you need some assistance I would be glad to collaborate with you. Cheers

**Comment by lazychaser** [comment]
Just continue using Cruddy and posting issues =) I would appreciate any ideas too
