### ISSUE TITLE
Change public path to public_html

### ISSUE THREAD

**Issue by mjedari** [cruddy/cruddy#126]
Hi,
I Wana change uploaded file path. So I want they save in public_html directory instead of public.
How can I do this?

**Comment by lazychaser** [comment]
```php
$repo->uploads('file')->relativelyTo(base_path('public_html'));
```

**Comment by mjedari** [comment]
Tanks,  but when I change public path directory my thamb images don't display in cruddy.
I think cruddy read images from public directory still. how can I solve it?

**Comment by lazychaser** [comment]
You can't, sorry. Thumbnails are only displayed when under public
directory. This is going to be changed in future after huge refactoring.

2016-03-03 12:10 GMT+03:00 mjedari <notifications@github.com>:

> Tanks, but when I change public path directory my thamb images don't
> display in cruddy.
> I think cruddy read images from public directory still. how can I solve it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cruddy/cruddy/issues/126#issuecomment-191667249>.
>



-- 
Best regards, Alexander Kalnoy.

**Comment by mjedari** [comment]
thank you very much.

**Comment by mjedari** [comment]
Excuse me, I didn't change public directory to other path. Now I use default . but I don't see Thumbnails still. In local all things is ok, but when upload them on sever and lunch it Thumbnails in cruddy don't display.I use addon domain to set public directory instead of public_html. Is there any way that change Thumbnail urls manually?
