### ISSUE TITLE
Add permissions to custom page

### ISSUE THREAD

**Issue by mgarciadelojo** [cruddy/cruddy#128]
Hi,

Thank you very much again for this awesome package.

I have already set up my permissions using another package, so, I can easily configure every user or role permissions in a few clicks, but, the thing is I am trying to create a custom controller inside the admin panel and I am trying to add permissions to this section as well. This is driving me crazy, because cruddy only checks for permissions when working with entities...

Do you have any idea how can I get it working?

Many thanks!

**Comment by lazychaser** [comment]
You can use whatever authorization method you want in your custom controller. I personally only apply specific middleware to all cruddy & custom backend routes.
