### ISSUE TITLE
Resize and crop image before store

### ISSUE THREAD

**Issue by mjedari** [cruddy/cruddy#131]
hi,
I want resize and crop images before store them. can i do this by cruddy built in function?
or if we have to use other package like https://github.com/Intervention/image , where should i use for example this : $img->resize(320, 240)  ?
thanks.

**Comment by lazychaser** [comment]
For now, there is no preprocessor available for uploader.

You can do this in the attribute setter. You need to check whether the image has changed and if it did, crop it and resave.

```php
public function setImageAttribute($value)
{
    if ($value == $this->attributes['image']) return;
    
    // crop image
    
    // And store it to the attributes
    $this->attributes['image'] = $value;
}
```

**Comment by mjedari** [comment]
Thanks a lot, i could do it.
