### ISSUE TITLE
Global Scope

### ISSUE THREAD

**Issue by mgarciadelojo** [cruddy/cruddy#133]
Hi again, @lazychaser,

I have set up a global scope in my model, but now, in the admin panel, using a relates field, the scope is also applied. Is there any way I can disable that scope in the admin panel? It's a bit frustrating that my users can't see their changes in the admin panel although the data is saved in the DB.

Many thanks,

**Comment by lazychaser** [comment]
Hi. Cruddy uses laravel's relations, so if you've set up global scope that affects them, then this is what you get. You won't be able to access the data associated with the relation since your scope is applied to the underlying query builder. What kind of scope are you using?

**Comment by mgarciadelojo** [comment]
A scope called publishable scope, to filter data based on their publish date. If the date is greater than the current one, then, the item won't show up but is also affecting the relates field.

**Comment by lazychaser** [comment]
Doesn't seem like this should be a global scope =) As an option, you can extend from base model, disable scope there and use that model in Cruddy.

**Comment by mgarciadelojo** [comment]
Good idea :) I'll check out it because is less work than changing all my eloquent queries... Thanks!!

**Comment by mgarciadelojo** [comment]
I am implementing it, but I am stucked with a little thing... I have a relation like this in my new model:

```
public function media()
{
    return $this->morphToMany('App\Models\Media', 'mediable');
}
```

And the Polymorphic relationship is always taking the name of my new model, obviously and I cannot find a way to override it in the model... Do you come up any idea?

Thank you in advance :)

**Comment by mgarciadelojo** [comment]
Eureka! I think this should do the trick...

```
    /**
     * Get the class name for polymorphic relations.
     *
     * @return string
     */
    public function getMorphClass()
    {
        return 'App\Models\Scene';
    }
```

**Comment by lazychaser** [comment]
Great!
