### ISSUE TITLE
Issue storing simple text

### ISSUE THREAD

**Issue by mgarciadelojo** [cruddy/cruddy#136]
Hi again!

I am building a simple banner management system and it lets my users add some banners with the following structure:

```
<ins data-revive-zoneid="..." data-revive-ct0="{clickurl_enc}" data-revive-id="..."></ins><script async src="..."></script>
```

The thing is I realized that when the string `</script>` is trying to be stored, they are unable to save the changes. The admin panel throws an error in the down side with the message "there was an error".

I can create them through tinker or migrations though.

Do you come up any idea about how can I solve it?

Thank you in advance :)

**Comment by lazychaser** [comment]
Hm, and what kind of error? What's on the console? What type of the field?

**Comment by mgarciadelojo** [comment]
The type of field is `text`, and the console output is:

```
vendor.js:7845 - POST http://example.com/backend/banners/77 403 (Forbidden)
```

Thanks!

**Comment by lazychaser** [comment]
403 means that user has not enough rights. Is it true that when you appending script tag you're unable to save and without script tag it works?

**Comment by mgarciadelojo** [comment]
Yes, that's it. But the thing is with the same database, when I try to save the `</script>` tag, in my homestead works but in production it doesn't...

**Comment by lazychaser** [comment]
Check your laravel.log for any errors and contents of failed request

**Comment by mgarciadelojo** [comment]
There is no errors in my logs :(

**Comment by mgarciadelojo** [comment]
I changed my `isPermitted` function to always return true, so I can test if the problem is about roles and permissions but it doesn't work either.

magically it works in homestead... I don't understand anything :(

**Comment by mgarciadelojo** [comment]
Could it be because `</script>` interferes with the Javascript library that is used to make the API calls to the backend? I don't know what can I do next...

**Comment by lazychaser** [comment]
You need to debug request and look where it throws 403 error

**Comment by mgarciadelojo** [comment]
Oh shit!! It's cloudflare. What a pain in the ass... Thank you for your help anyways. Really apreciated!

**Comment by lazychaser** [comment]
It's a hosting? It forbids <script> inside request body?

**Comment by h-collector** [comment]
Just for the info maybe he had:
Rocket Loader enabled => https://www.cloudflare.com/features-optimizer/
I had also some problems with this feature as it interferes with script tags.

**Comment by mgarciadelojo** [comment]
Yes, I have it, but the thing is the error shows up only when in the body
of the request is a `<script>` tag...

Anyways, thank you for the info :)
