### ISSUE TITLE
Uploading to S3

### ISSUE THREAD

**Issue by dddbliss** [cruddy/cruddy#137]
So I have a use case where I want to be able to upload images, but not through the repo to local filesystem but instead into s3. Is there a way to capture the uploaded file and use Laravel 5's Storage to save it to S3, update the model before saving?

Poking around it doesn't seem immediately clear, so looking for some guidance on where to start.

**Comment by lazychaser** [comment]
In future release you can simply specify at which disk/filesystem to upload files. For now, you can override [base repository](https://github.com/cruddy/cruddy/blob/master/src/Repo/AbstractEloquentRepository.php), particullary [this method](https://github.com/cruddy/cruddy/blob/master/src/Repo/AbstractEloquentRepository.php#L375), and return custom repo from [this method](https://github.com/cruddy/cruddy/blob/master/src/Entity.php#L589) on entity.

**Comment by dddbliss** [comment]
Awesome, I will give that a shot, thanks for the information.

**Comment by foxhound87** [comment]
please support https://github.com/minio/minio

thank you
