### ISSUE TITLE
Auth::check in middleware return false always

### ISSUE THREAD

**Issue by hellosaeedalizadeh** [cruddy/cruddy#147]
I have no Idea why Auth::check() always return false in middleware that I attach to cruddy config file?

I do this with Sentinel package and it was the same

I test in another route to sure middleware is correct and it was, but in cruddy not working !

please help me

**Comment by lazychaser** [comment]
Show me your config file

**Comment by hellosaeedalizadeh** [comment]
in config of cruddy : 
'middleware' => 'backend',

middleware :  

<?php

namespace App\Http\Middleware;

use Closure;
use Cartalyst\Sentinel\Laravel\Facades\Sentinel;

class BackendAuth
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if (Sentinel::check()) {
            return $next($request);
        }else{
            return redirect('login');
        }
    }
}

kernel : 
protected $routeMiddleware = [
        'backend' => \App\Http\Middleware\BackendAuth::class,
    ];

**Comment by lazychaser** [comment]
Cruddy version?

**Comment by hellosaeedalizadeh** [comment]
"kalnoy/cruddy": "0.5.*@dev",

**Comment by ehsanmnz** [comment]
in laravel 5.2 with custom loginName in sentinel first create a custom user model that extends Cartalyst\Sentinel\Users\EloquentUser and with in change protected $loginNames to what ever you want
second in config of sentinel change the user model used in Sentinel and finally in cruddy config
in middleware section add ['web', 'YourCustomMiddleware']

**Comment by hellosaeedalizadeh** [comment]
thanks indeed :)
