### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by MohammadAzad** [cruddy/cruddy#151]
hi,
how i can add label(in lang file) for head of sub menu?
and how i can add label(in lang file) for brand title?
@lazychaser 
@ehsanmnz

**Comment by lazychaser** [comment]
https://github.com/cruddy/cruddy/wiki/Localization

**Comment by MohammadAzad** [comment]
I use that link, but doesn't work for menus which has child menu.

**Comment by lazychaser** [comment]
It works for entities, doesn't matter where it placed. If you need to localize custom menu item, you can specify language key instead of text.
