### ISSUE TITLE
newQuery in models does not work on cruddy

### ISSUE THREAD

**Issue by vahidRP** [cruddy/cruddy#160]
Hi!
I have a model called "User" and an entity called "UserEntity" that is for User Model. When i open UserEntity i want to see just activated user which is filtered by a boolean column. In this case i override newQuery function in User Model and wrote "$query->where("activated" , 1)". This query works fine but in cruddy doesn't work. what should i do for filtering user as default ?

@lazychaser

**Comment by lazychaser** [comment]
Hi. You should look towards custom repository (there is a method that provides a repo, you can override it in entity)

**Comment by vahidRP** [comment]
Thank you for your help.
i overrided index function form entity into my entity, like this:

public function index(array $options)
    {
        $results = $this->getRepository()->search($options, $this->getSearchProcessor($options));

//        Filter Items By Me
        $items = [];
        foreach ($results["items"] as $item){
            if($item->active) $items[] = $item;
        }
        $results["items"] = $items;
//        Up to here

        if (array_get($options, 'simple')) {
            $results['items'] = $this->simplifyAll($results['items']);
        } else {
            $results['items'] = $this->extractAll($results['items'],
                $this->getColumns());
        }

        return $results;
    }

It works correct but this filter is after fetching data from database. How can i do it before query?
@lazychaser

**Comment by lazychaser** [comment]
You need to override [createRepository](https://github.com/cruddy/cruddy/blob/master/src/Entity.php#L589) method and return an instance of [AbstractEloquentRepository](https://github.com/cruddy/cruddy/blob/master/src/Repo/AbstractEloquentRepository.php) where you can override `newQuery`. This is much simpler to do in newer dev version which I mentioned in your other issue.

**Comment by vahidRP** [comment]
Thank you very much. It worked.
