### ISSUE TITLE
Russian characters in "date" columns

### ISSUE THREAD

**Issue by thylo** [cruddy/cruddy#18]
![index](https://cloud.githubusercontent.com/assets/1242863/3081243/913ff864-e4bc-11e3-856d-b5993611d438.png)

Bug occuring with Firefox 29.0.1 OSX, working fine with Chrome OSX

**Comment by flinguin** [comment]
stumbeled acros this issue too ...
seem to me that the moment.js locale falls back to russian if any other app language than en is set ...
anny suggestions on how to fix this or any workaround ? :)

**Comment by lazychaser** [comment]
Fixed this
