### ISSUE TITLE
Cruddy and Laravel 5

### ISSUE THREAD

**Issue by ehsanmnz** [cruddy/cruddy#55]
Is there any plan for integrating cruddy with Laravel 5 ?

**Comment by lazychaser** [comment]
First iteration that supports l5 is at `0.5.0@dev`

**Comment by ehsanmnz** [comment]
playing with this version now, thanks

**Comment by MohammadAzad** [comment]
when will cruddy for laravel5 comes?

**Comment by lazychaser** [comment]
Don't know yet, I'm bussy with migrating my project, after that I'll continue on migrating cruddy. You still can use `0.5.0@dev` version which works on L5, though not much test have been made.

**Comment by MohammadAzad** [comment]
Thank you

**Comment by ehsanmnz** [comment]
cruddy 0.5.* throw TokenMismatchException in delete a record from an entity

**Comment by lazychaser** [comment]
Yeeeah, thanks

**Comment by sparkeleven** [comment]
Any updates on plans to update for Laravel 5?

**Comment by lazychaser** [comment]
@sparkeleven Hi, Cruddy 0.5.*@dev works with Laravel 5. But when to release I don't know yet.

**Comment by lazychaser** [comment]
Cruddy v0.5 has been realeased with support of l5.1 and 5.2
