### ISSUE TITLE
Multiple combo box

### ISSUE THREAD

**Issue by poor-coder** [cruddy/cruddy#86]
How can make a multiple combo box field?

**Comment by lazychaser** [comment]
Hi. Sorry, its not possible yet. Why would you need such feature anyway?
20 ñÎ× 2015 Ç. 14:56 ÐÏÌØÚÏ×ÁÔÅÌØ "poor-coder" <notifications@github.com>
ÎÁÐÉÓÁÌ:

**Comment by poor-coder** [comment]
i want something like choose tags for post in cruddy-demo but not in relation ,
for example for users , they can have different roles and admin can choice that roles

**Comment by lazychaser** [comment]
Multiple enums are supported in v0.5:

```php
$schema->enum('role', [...])->multiple();
```
