### ISSUE TITLE
Morphable select list

### ISSUE THREAD

**Issue by jgkinnear** [cruddy/cruddy#88]
I have a requirement to have a morphable table pick which resource it related to. For example,

Student
 - morphsOne('Address', 'addressable')

Staff
 - morphsOne('Address', 'addressable')

Address
 - Addressable_id
 - Addressable_type

I want to be able to create a new Address and pick which student or staff it belongs to. Is this supported (I couldn't find any examples) or can you suggest how I could possible work around this (I was thinking maybe using contraints?)

Thanks (p.s. is there a repository for the cruddy playground example?)

**Comment by lazychaser** [comment]
Hi!

This functionality is not supported yet, for now you can only instantiate Adress from related entity using [embedded forms](https://github.com/cruddy/cruddy/wiki/Fields#embedding-forms).

> p.s. is there a repository for the cruddy playground example?

Sorry, but now. It's really simple, it uses very basic features and no magic.
