### ISSUE TITLE
problem with Complex filters

### ISSUE THREAD

**Issue by poor-coder** [cruddy/cruddy#89]
Hi,
when I add protected $filters in schema , It shows "Couldn't load the schema."
![untitled](https://cloud.githubusercontent.com/assets/5454897/6128619/a8c395d8-b14c-11e4-8c19-0c9a1e70864c.png)

**Comment by lazychaser** [comment]
Hi!

Actually, strings do not support separate filters =) You can use search box for filtering text data, it something like "search anywhere"

**Comment by poor-coder** [comment]
Thanks !
