### ISSUE TITLE
Notification for updated/unseen entities

### ISSUE THREAD

**Issue by ehsanmnz** [cruddy/cruddy#90]
Is there some way to notify users for updated/unseen entities after log in ?

for example if one new student register to the system and the student's entity has that,  show number 1 or some thing in menu bar near the students link

**Comment by lazychaser** [comment]
Hi! You can use `badge` [option](https://github.com/lazychaser/illuminate-menu#item-options) of menu item. You can provide a clusure there. It will show badge when the page is rendered.

**Comment by ehsanmnz** [comment]
when user see the new updated entities, the badge value must be remove, I'll try to write some simple javascript code that when user click on menu item and see the entities record the badge class or whole DOM node remove
Is this appropriate way?

**Comment by lazychaser** [comment]
I thought about this already, i.ll add this in future versions, but you can
write your own script for now
12 æÅ× 2015 Ç. 21:25 ÐÏÌØÚÏ×ÁÔÅÌØ "ehsanmnz" <notifications@github.com>
ÎÁÐÉÓÁÌ:
