### ISSUE TITLE
ErrorException in MenuBuilder.php

### ISSUE THREAD

**Issue by ehsanmnz** [cruddy/cruddy#91]
Argument 1 passed to Illuminate\Html\MenuBuilder::__construct() must be an instance of Illuminate\Http\Request, instance of Illuminate\Html\HtmlBuilder given

I changed a bit Kalnoy\Cruddy\Service\MenuBuilder::__constructor to this
parent::__construct($request); 
and now the exception gone

**Comment by lazychaser** [comment]
Thanks!
