### ISSUE TITLE
Imageuploads in ebedded Forms

### ISSUE THREAD

**Issue by flinguin** [cruddy/cruddy#92]
I ' working on a Project where multiple Entities (eg. Posts, Athletes, Sports) should provide the possibility of linking 1-n Images - im trying to do this via embedded Forms (of the Image entity) in the respective other entities (Posts, Athletes, Sports)

Image upload works fine if i create an image-entry directly but when adding Images to another entity via embedded forms i get a 500-error when trying to save the (eg.) Post

i am not even sure if file/image-uploads are supposed to work with embedded forms or what is causing the 500-error otherwise.

trying to save a post with one embedded image-entity look something like this:

![cruddy-embedded-images1](https://cloud.githubusercontent.com/assets/4098639/6318801/a5fa6dd4-baa4-11e4-86d7-3c5063145489.png)

**Comment by flinguin** [comment]
seems to be an issue of the dev-master branch (0.5-dev)
with 0.4 everything works just as expected

**Comment by lazychaser** [comment]
v0.5.*@dev is intended to be used with Laravel 5 and not backward-compatible. If you aware of that and you did run this on L5, then please provide exception info from log file.

**Comment by lazychaser** [comment]
There was an issue with embedded forms that is now fixed.
