### ISSUE TITLE
laravel 5 and embed form

### ISSUE THREAD

**Issue by ehsanmnz** [cruddy/cruddy#93]
Hi, when i try to save a embed model this exception has been thrown:

ErrorException in InnerDataCollection.php
Argument 1 passed to Kalnoy\Cruddy\InnerDataCollection::save() must be an instance of Eloquent, instance of App\Models\Workshop given

when I remove Type Hint of save() method the exception gone and db record is update

**Comment by lazychaser** [comment]
Hi, please, update to recent version `composer update`.

**Comment by ehsanmnz** [comment]
Thanks
