### ISSUE TITLE
laravel 5 Relational types Fields

### ISSUE THREAD

**Issue by ehsanmnz** [cruddy/cruddy#95]
Hi!

In BelongsTo... relations when try to show list of another entity in drop down, all things done (call backend/run query/return appropriate response) but when app.js try too show list this exception happen:
 Cannot read property 'length' of undefined (app.js line 508)

**Comment by lazychaser** [comment]
Hi!

Please, update to recent version.

**Comment by ehsanmnz** [comment]
still same result after update and publish

**Comment by lazychaser** [comment]
You need to call this to publish:

```
php artisan vendor:publish --tag cruddy --force
```

**Comment by ehsanmnz** [comment]
Thanks
