### ISSUE TITLE
Slug

### ISSUE THREAD

**Issue by ehsanmnz** [cruddy/cruddy#96]
in my fields method I have $schema->slug('slug','title') , if title field fills with UTF characters, the slug filed only remain with - (or other separators) but with English title works fine

**Comment by ehsanmnz** [comment]
is there problem if remove this check in JavaScript, chars = options.chars ? "a-z0-9\-_" ?

**Comment by lazychaser** [comment]
You can specify your own chars, i.e. I used this to support russian chars:

```php
$schema->slug('slug')->chars('a-z\u0430-\u044f0-9\-_');
```

**Comment by ehsanmnz** [comment]
Thanks

**Comment by lazychaser** [comment]
I refactored slug in v0.5.4, it now uses str_slug to convert chars when you click save

**Comment by ehsanmnz** [comment]
my slug's characters convert to english when click save

**Comment by lazychaser** [comment]
@ehsanmnz this is what `str_slug` does

**Comment by ehsanmnz** [comment]
thanks
